### ISSUE TITLE
Out of bounds exception during clustering for jmm9018

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#252]
I got this error when running ReCiter for jmm9018.

```
16:09:45.236 [http-nio-5000-exec-1] INFO  r.a.c.a.s.ReCiterArticleScorer - ******************** Cluster 1 scoring starts **********************
16:09:45.300 [http-nio-5000-exec-1] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IndexOutOfBoundsException: Index: 2, Size: 2] with root cause
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at reciter.algorithm.evidence.targetauthor.name.strategy.ScoreByNameStrategy.checkToIgnoreNameVariants(ScoreByNameStrategy.java:841)
	at reciter.algorithm.evidence.targetauthor.name.strategy.ScoreByNameStrategy.executeStrategy(ScoreByNameStrategy.java:45)
	at reciter.algorithm.evidence.targetauthor.AbstractTargetAuthorStrategyContext.executeStrategy(AbstractTargetAuthorStrategyContext.java:38)
	at reciter.algorithm.cluster.article.scorer.ReCiterArticleScorer.runArticleScorer(ReCiterArticleScorer.java:308)
	at reciter.engine.ReCiterEngine.run(ReCiterEngine.java:175)
	at reciter.controller.ReCiterController.runFeatureGenerator(ReCiterController.java:303)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

**Comment by paulalbert1** [comment]
Fixed. Thanks.
