### ISSUE TITLE
Error in running dynamoDb locally in Docker

### ISSUE THREAD

**Issue by smierz** [wcmc-its/ReCiter#452]
**Describe the bug**
I want to run ReCiter with a local dynamoDb in Docker, but sqlite4java throws an error because it can not find its native-libs (see below)

**To Reproduce**
1. I cloned the repo and changed the following properties: 
spring.security.enabled=false
aws.dynamoDb.local=true
aws.dynamoDb.local.dbpath=/app
aws.s3.use=false
use.scopus.articles=false

2. After that I did `mvn install`
3. docker build + run

`com.almworks.sqlite4java.SQLiteException: [-91] cannot load library: com.almworks.sqlite4java.SQLiteException: [-91] sqlite4java cannot find native library                        
at com.almworks.sqlite4java.SQLite.loadLibrary(SQLite.java:97) ~[sqlite4java-1.0.392.jar!/:392]                                                                             at com.almworks.sqlite4java.SQLiteConnection.open0(SQLiteConnection.java:1441) ~[sqlite4java-1.0.392.jar!/:392]                                                             at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:282) ~[sqlite4java-1.0.392.jar!/:392]                                                               at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:293) ~[sqlite4java-1.0.392.jar!/:392]                                                               at com.almworks.sqlite4java.SQLiteQueue.openConnection(SQLiteQueue.java:464) ~[sqlite4java-1.0.392.jar!/:392]                                                               at com.almworks.sqlite4java.SQLiteQueue.queueFunction(SQLiteQueue.java:641) ~[sqlite4java-1.0.392.jar!/:392]                                                                at com.almworks.sqlite4java.SQLiteQueue.runQueue(SQLiteQueue.java:623) ~[sqlite4java-1.0.392.jar!/:392]                                                                     at com.almworks.sqlite4java.SQLiteQueue.access$000(SQLiteQueue.java:77) ~[sqlite4java-1.0.392.jar!/:392]                                                                    at com.almworks.sqlite4java.SQLiteQueue$1.run(SQLiteQueue.java:205) ~[sqlite4java-1.0.392.jar!/:392]                                                                        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]                                                                                                          Caused by: com.almworks.sqlite4java.SQLiteException: [-91] sqlite4java cannot find native library                                                                                   at com.almworks.sqlite4java.Internal.loadLibraryX(Internal.java:136) ~[sqlite4java-1.0.392.jar!/:392]                                                                       at com.almworks.sqlite4java.SQLite.loadLibrary(SQLite.java:95) ~[sqlite4java-1.0.392.jar!/:392]                                                                             ... 9 common frames omitted  `

**Comment by sarbajitdutta** [comment]
@smierz Would you tell us what version of docker you are using? What is the OS you are using and its version?
Did you try the application without docker? Also, I should mention we recently updated the master branch to use Java 11 as default. You can try to downgrade to Java 8 if you wish.

**Comment by smierz** [comment]
I'm using docker version 20.10.2 on Windows 10.

I'm able to run the application without docker ( I have Java 11 installed and used it to compile the application, no errors)

**Comment by sarbajitdutta** [comment]
@smierz We have designed the dynamodb local to run without docker. The docker version is for production when you want to connect to actual dynamodb service. You can run the application without docker with dyanmodb local.  If you absolutely have to use docker you need to use docker-compose to separate the app and the dynamodb local as separate service and modify the file here https://github.com/wcmc-its/ReCiter/blob/master/src/main/java/reciter/database/dynamodb/DynamoDbConfig.java#L127-L140. You need to change localhost to match the local DNS `docker.for.win.localhost` (since you are on Windows)

For details you can refer to official dynamodb docs - 
https://github.com/awsdocs/amazon-dynamodb-developer-guide/blob/master/doc_source/DynamoDBLocal.DownloadingAndRunning.md

https://stackoverflow.com/a/53583725

Let me know if that answer your issue.

**Comment by smierz** [comment]
yes, thank you, this is working for me!

Two notes for documentation:
* in DynamoDbConfig.java I had to use "http://docker.for.win.host.internal" since docker is running on Windows
* the volume on the host system that is used in docker-compose needs to be writable by docker (set permissions)

**Comment by sarbajitdutta** [comment]
@smierz thank you confirming the fix. I will update the documentation to reflect the host for windows with docker. Are you planning to set it up in AWS?

**Comment by smierz** [comment]
hm no, I don't think so.

btw if you update the README: 
since swagger 3.0 the address changed from /swagger-ui.html --> /swagger-ui/ or /swagger-ui/index.html

**Comment by smierz** [comment]
update: I replaced "docker.for.win.host.internal"  in DynamoDbConfig with "http://dynamo", so I'm using the service that is available in the default network of docker-compose (OS-independent)
